language: clojure
jdk:
  - oraclejdk8
script:
  - export PROJ_BASE=`echo "${PWD##*/}"`
  - lein eastwood "{:namespaces [${PROJ_BASE}.core]}"
  - lein ancient
  - JAVA_OPTS="-Xms256M -Xmx512M -Xss512M" lein spec
